# Generated by Django 4.2.7 on 2023-11-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_alter_recipe_photo_alter_recipe_steps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='recipes',
        ),
        migrations.AddField(
            model_name='recipe',
            name='categories',
            field=models.ManyToManyField(to='recipe.category'),
        ),
    ]
